// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opdpguundnymkabhdytc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZHBndXVuZG55bWthYmhkeXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTk3MTEsImV4cCI6MjA1NjU5NTcxMX0.xoS3sCJfG8bJo0inxkLvoKxyimvMnQT8Mdv7lUzR9oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);